In [44]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array( list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [45]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [46]:
type(array_list)

numpy.ndarray

In [47]:
list_

['1', '2', '3', '4', '5']

In [48]:
type(list_)

list

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [49]:
for i in list_:
    print(f'value : {(i)}, datatype : {type(i)}')

value : 1, datatype : <class 'str'>
value : 2, datatype : <class 'str'>
value : 3, datatype : <class 'str'>
value : 4, datatype : <class 'str'>
value : 5, datatype : <class 'str'>


In [50]:
for i in array_list:
    print(f'value : {(i)}, datatype : {type(i)}')

value : 1, datatype : <class 'numpy.str_'>
value : 2, datatype : <class 'numpy.str_'>
value : 3, datatype : <class 'numpy.str_'>
value : 4, datatype : <class 'numpy.str_'>
value : 5, datatype : <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

In [52]:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [53]:
array_list

array([1, 2, 3, 4, 5])

In [54]:
type(array_list)

numpy.ndarray

Yes, There is a difference in datatypes of elements present in both lists.
List elements have data type string and array_list have datatype numpy integer.

In [55]:
for i in array_list:
    print(f'value : {(i)} , datatype : {type(i)}')

value : 1 , datatype : <class 'numpy.int64'>
value : 2 , datatype : <class 'numpy.int64'>
value : 3 , datatype : <class 'numpy.int64'>
value : 4 , datatype : <class 'numpy.int64'>
value : 5 , datatype : <class 'numpy.int64'>


In [26]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [28]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.shape(num_array)

(2, 3)

In [29]:
np.size(num_array)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [36]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])